# Generated by Django 3.2.5 on 2021-07-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ketua', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('no_telepon', models.CharField(max_length=100)),
                ('instansi', models.CharField(max_length=100)),
                ('prodi_ketua', models.CharField(max_length=100)),
                ('nama_anggota', models.CharField(max_length=100)),
                ('prodi_anggota', models.CharField(max_length=100)),
                ('subtema', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Poster',
                'db_table': 'Poster',
            },
        ),
    ]
