# Generated by Django 3.2.5 on 2021-07-29 13:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('judul', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('isi', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News',
                'db_table': 'News',
            },
        ),
    ]
