# Generated by Django 3.2.5 on 2021-07-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prototype',
            fields=[
                ('id_pendaftaran', models.AutoField(primary_key=True, serialize=False)),
                ('nama_ketua', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('no_telepon', models.CharField(max_length=100)),
                ('instansi', models.CharField(max_length=100)),
                ('prodi_ketua', models.CharField(max_length=100)),
                ('nama_anggota1', models.CharField(max_length=100, null=True)),
                ('prodi_anggota1', models.CharField(max_length=100, null=True)),
                ('nama_anggota2', models.CharField(max_length=100, null=True)),
                ('prodi_anggota2', models.CharField(max_length=100, null=True)),
                ('subtema', models.CharField(max_length=100)),
                ('file_pdf', models.FileField(upload_to='poster/file_lomba')),
            ],
            options={
                'verbose_name_plural': 'Prototype',
                'db_table': 'Prototype',
            },
        ),
    ]
